#!/bin/sh

set -eu

branch=$(git rev-parse --abbrev-ref HEAD)
[[ "$branch" == "master" ]] || exit 0

black openpipe
ENGINES="single multi"
for engine in $ENGINES; do
    export OPENPIPE_ENGINE="$engine"
    tox
    tox -e run openpipe/demos/run_all_demos.yaml
    scripts/test_extra_actions.sh
done
