__title__ = "Openpipe"
__version__ = "0.0.118"
__summary__ = "A human friendly data-oriented integration toolkit"
__uri__ = "https://www.openpipe.org"
__author__ = "João Pinto"
__email__ = "lamego.pinto@gmail.com"
__license__ = "APACHE-2"
